//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crossovki3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Data_BaseEntities_Unrecognized : DbContext
    {
        public Data_BaseEntities_Unrecognized()
            : base("name=Data_BaseEntities_Unrecognized")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<f_REPORT_Mega_Base_Get_Catalogue_Result> f_REPORT_Mega_Base_Get_Catalogue(string maker, Nullable<int> supplier_id)
        {
            var makerParameter = maker != null ?
                new ObjectParameter("maker", maker) :
                new ObjectParameter("maker", typeof(string));
    
            var supplier_idParameter = supplier_id.HasValue ?
                new ObjectParameter("supplier_id", supplier_id) :
                new ObjectParameter("supplier_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_REPORT_Mega_Base_Get_Catalogue_Result>("f_REPORT_Mega_Base_Get_Catalogue", makerParameter, supplier_idParameter);
        }
    
        public virtual ObjectResult<f_REPORT_Mega_Base_Unrecognized__Result> f_REPORT_Mega_Base_Unrecognized_(Nullable<int> supplier_id)
        {
            var supplier_idParameter = supplier_id.HasValue ?
                new ObjectParameter("supplier_id", supplier_id) :
                new ObjectParameter("supplier_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_REPORT_Mega_Base_Unrecognized__Result>("f_REPORT_Mega_Base_Unrecognized_", supplier_idParameter);
        }
    }
}
